feat: navigation 구현
ToyVallet/swifty-fe pull request #3
Opened 2024-05-13 04:07 UTC by kd02109

## Navigation 구현

- position fixed를 통해 항상 상단에 고정되도록 했습니다.
- group route를 활용하여 디자인에 맞는 layout을 사용할 수 있도록 prop을 조정할 수 있습니다.
- https://6617cc6b749cda32414848fb-bifjsqvsad.chromatic.com/

2024-05-14 00:30 UTC, ho991217 requested changes
danfesta 코드를 많이 재활용하신것으로 보이는데, 구조적으로 많은 변화가 있는 만큼 수정이 조금 더 있으면 어떨까합니다!!

2024-05-14 00:30 UTC, ho991217 commented on app/components/common/navigation/index.tsx
돋보기가 우측에 패딩없이 바짝 붙는 것 같습니다!

2024-05-14 00:30 UTC, ho991217 commented on app/components/common/navigation/index.tsx
> +            <IoArrowBackOutline size={25} className={'text-white'} />
`className=""` 대신 `className={''}`으로 써주신 이유가 있나요?

2024-05-14 00:30 UTC, ho991217 commented on app/components/common/navigation/index.tsx
> +  scheme?: 'light' | 'dark';
필요없는 옵션 같네요!

2024-05-14 00:30 UTC, ho991217 commented on app/components/common/navigation/index.tsx
> +  isLogo?: boolean;
'로고를 가지고 있'는지에 대한 property네요, 그렇다면 `is`보다는 `has`라는 접두사가 더 잘 어울리지 않을까요?

2024-05-14 00:30 UTC, ho991217 commented on app/components/common/navigation/index.tsx
> +import { If } from '@/app/components/util';
```suggestion
import { BackButton, Link } from '@components/common/';
import LogoLink from '@components/common/navigation/logo-link';
import { If } from '@components/util';
```

2024-05-14 00:30 UTC, ho991217 commented on app/components/common/navigation/index.tsx
> +  hasBackButton?: boolean;
상단바에 다양한 variant가 있습니다.
1. 검색 버튼이 있는 경우
2. 뒤로가기 버튼과 로고가 있는 경우
3. 뒤로가기 버튼과 경로 이름이 있는 경우

이 case 들이 위치값도 다르며, 공유하는 부분이 많지 않은데요,
그렇다면 단순히 boolean 옵션으로 구분하는 것 보다는 variant로 구분하는 것은 어떤가요?

2024-05-14 00:30 UTC, ho991217 commented on app/components/common/navigation/index.tsx
화면 너비가 max-width를 넘어가면 padding 값이 변하네요!

2024-05-14 00:30 UTC, ho991217 commented on app/components/common/navigation/index.tsx
<img width="391" alt="스크린샷 2024-05-14 09 28 26" src="https://github.com/ToyVallet/swifty-fe/assets/84632077/da23f282-3699-46dc-94e7-b98a9059ea21">
모바일 환경에서 정상적으로 보이지 않네요!

2024-05-14 04:13 UTC, hyunwlee-dev approved these changes
수고하셨습니다!!

2024-05-14 05:33 UTC, kd02109 commented
https://6617cc6b749cda32414848fb-kqolzszxjb.chromatic.com/

수정사항을 반영했습니다. 
navigation을 3가지 상황으로 분리해서 variant prop만으로 컨트롤 할 수 있도록 구조를 변경했습니다.

일부 자잘한 css 미스매치를 수정했습니다.

2024-05-15 06:36 UTC, ho991217 approved these changes
캬 좋네요 👍👍👍

2024-05-15 06:36 UTC, merged