feat: hero
ToyVallet/swifty-fe pull request #7
Opened 2024-05-13 11:03 UTC by kd02109

- Hero component 구현
- 상단 Hero에 페이지에 맞는 component가 들어갈 수 있도록 작성
- festival 데이터에 맞는 type 지정
<img width="137" alt="image" src="https://github.com/ToyVallet/swifty-fe/assets/57277708/8ad0ca8f-9486-4dab-be30-9270c05cba79">

- storybook 구성 (https://6617cc6b749cda32414848fb-ivnddibuai.chromatic.com/)
close #6

2024-05-14 01:24 UTC, ho991217 requested changes
수고하셨습니다! 몇 가지 질문이 있었네용

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/index.tsx
> +  isCarousel?: boolean;
어떤 옵션인지 잘 모르겠습니다.

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/index.tsx
> +      <div className="bg-bgBlack absolute bottom-0 w-full max-h-[40px] h-[15%] z-10 rounded-t-[22px]"></div>
```suggestion
      <div className="bg-bgBlack absolute bottom-0 w-full max-h-10 h-[15%] z-10 rounded-t-[22px]"></div>
```

대신 arbitrary value를 사용하신 이유가 있나요?

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/hero-carousel.tsx
> +import { Festival } from '@/app/lib/types';
```suggestion
import { IntlProvider } from '@components/common';
import HeroTile from '@components/common/hero/hero-tile';
import { Festival } from '@lib/types';
```

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/index.tsx
> +    <div
`hero`는 `section`의 명칭입니다. 여기에서는 `<div />` 태그로 작성되었는데요, `<section />`태그가 더 시멘틱하지 않을까요?

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/hero-tile.tsx
> +import parserDate from '@/app/lib/utils/parser/parser-date';
```suggestion
import { Link } from '@lib/navigation';
import { Festival } from '@lib/types';
import parserDate from '@lib/utils/parser/parser-date';
```

2024-05-14 01:24 UTC, ho991217 commented on app/lib/utils/parser/parser-date.ts
`parser`라는 prefix가 붙었는데요, 'parser'는 '파싱을 수행하는 함수'라는 의미가 됩니다. 그렇다면 'dateParser'의 어순이 더 어울리지 않을까요?

2024-05-14 01:24 UTC, ho991217 commented on app/lib/utils/parser/parser-date.ts
혹은, 동사의 형태로 `parseDate` 로 사용할 수 있겠네요!

2024-05-14 01:24 UTC, ho991217 commented on app/lib/utils/parser/parser-date.ts
함수의 역할에 대해서도 다시 생각해보시면 좋을 것 같습니다. 
잘 보시면, 이 함수는 `파싱`이 아니라 `포맷팅`을 해주고 있어요

2024-05-14 01:24 UTC, ho991217 commented on app/lib/utils/parser/parser-date.ts
> +  return `${start_day[0]}년 ${start_day[1]}월 ${start_day[2]}일 - ${end_day[2]}일`;
행사 일정이 2024년 12월 31일 ~ 2025년 1월 1일이라면 이 함수는 어떻게 동작해야할까요?

2024-05-14 01:24 UTC, ho991217 commented on app/lib/utils/parser/parser-date.ts
> +  const end_day = end.split('-');
이 함수가 어떤 동작을 하는 함수인지 한눈에 들어오지 않는 것 같습니다. 실제 사용하신 부분을 보지 않고, 이 함수만 보면 뭐 하기위한 함수인지 잘 모르겠어요.

2024-05-14 01:24 UTC, ho991217 commented on app/lib/types/types.ts
> +}
이 둘은 어떤 차이가 있나요? 둘 다 결국은 DTO일텐데, 동일한 네이밍 같습니다.

2024-05-14 01:24 UTC, ho991217 commented on app/lib/types/types.ts
> +  festivalStatus: 'BEFORE' | '';
`'BEFORE'` 혹은 `''` 인값인가요?

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/hero-tile.tsx
> +    <Link href={'#'} className="relative flex-[0_0_100%] overflow-hidden">
클릭해도 해당 링크로 넘어가지 않는 것 같습니다.

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/hero-tile.tsx
> +          loading="eager"
lazy load를 사용하지 않으신 이유가 있나요?

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/hero-tile.tsx
> +        </div>
```suggestion
        <div className="text-xl font-semibold">
          <h4>{name}</h4>
          <h4>{description}</h4>
        </div>
```
로 단축시킬 수 있을 것 같습니다

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/hero-tile.tsx
> +          <h4 className="text-xl font-semibold">{description}</h4>
description은 span 태그가 더 시멘틱하지 않을까요?

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/hero-carousel.tsx
> +  }, [emblaApi]);
이 부분은 어떤 코드인지 설명해줄 수 있나요?

2024-05-14 01:24 UTC, ho991217 commented on app/components/common/hero/hero-carousel.tsx
carousel 과 같은 컴포넌트는 상당히 많이 쓰일 것 같습니다. 공통 컴포넌트로 우선 분리하고, 히어로 섹션을 위한 컴포넌트로 한번 더 래핑하는 것은 어떨까요?

2024-05-14 01:26 UTC, ho991217 requested changes

2024-05-14 01:26 UTC, ho991217 commented on app/components/common/hero/hero-tile.tsx
이미지가 늘어나거나 눌려서 비정상적으로 보입니다.
<img width="646" alt="스크린샷 2024-05-14 10 26 14" src="https://github.com/ToyVallet/swifty-fe/assets/84632077/f26877d1-c0b8-48e4-92c1-3afeb44ac5f6">

2024-05-14 03:56 UTC, hyunwlee-dev approved these changes
수고하셨습니다!!

2024-05-14 03:56 UTC, hyunwlee-dev commented on app/components/common/hero/hero-carousel.tsx
home안에 hero-tiles를 만들어서 tiles 컨벤션을 맞추면 좋을 것 같습니다

2024-05-14 03:56 UTC, hyunwlee-dev commented on app/components/common/hero/hero-tile.tsx
> +          className="object-fill"
object-cover를 사용하는 것이 이미지 비율에 더 좋을 것 같습니다.

2024-05-14 03:56 UTC, hyunwlee-dev commented on app/lib/utils/parser/parser-date.ts
> +  const end_day = end.split('-');
replaceAll('-', '.') 사용이 더 직관적일 것 같습니다!

2024-05-14 05:48 UTC, kd02109 commented on app/components/common/hero/index.tsx
> +  isCarousel?: boolean;
해당 옵션이 main page에서는 hero 영역에 carousel이 들어가고 축제 상세 페이지에서는 image만 들어가게 되는데
이때 hero 영역의 height이 변경되어서 hero height을 control 하기 위한 prop입니다.

2024-05-14 05:51 UTC, kd02109 commented on app/lib/types/types.ts
> +  festivalStatus: 'BEFORE' | '';
이 부분은 아직 서버쪽에서 fesivalStatus에 관한 상세 정보를 전달받지 못해서 위와 같이 처리 했습니다.

2024-05-14 05:54 UTC, kd02109 commented on app/components/common/hero/hero-tile.tsx
> +          loading="eager"
이 부분은 수정하도록 하겠습니다.

2024-05-14 05:56 UTC, kd02109 commented on app/components/common/hero/hero-carousel.tsx
> +  }, [emblaApi]);
해당 코드는 hero carousel에서 몇 번째 data를 보여주는지 표시하기 위해 추가한 기능입니다. 1/10, 2/10 과 같이요

2024-05-14 05:58 UTC, kd02109 commented on app/components/common/hero/hero-tile.tsx
> +    <Link href={'#'} className="relative flex-[0_0_100%] overflow-hidden">
개발 환경에서 정상적으로 동작하고 있는것 같은데, 어떤 부분에서 router가 잘 동작되지 않는 것 같나요?

2024-05-14 06:10 UTC, kd02109 commented on app/components/common/hero/hero-tile.tsx
이 부분은 현재 이미지를 해당 영역 전체에 맞춰서 다 보여주도록 했는데, 이때 현재 이미지 크기와 맞지 않아서 깨지는 것 같습니다.

2024-05-14 06:17 UTC, kd02109 commented on app/components/common/hero/hero-tile.tsx
> +          className="object-fill"
호연님이 위에서 말씀해주신 컨벤션이 어떤 것을 말씀하시는지 이해가 잘 안되는데 풀어서 상세히 설명해주실 수 있을까요?

2024-05-14 06:32 UTC, hyunwlee-dev commented on app/components/common/hero/hero-tile.tsx
> +          className="object-fill"
기존 tile관련한 파일들이 모두 home폴더안에 위치해 있어서요. common/hero폴더안에 hero관련 모두 넣어놔도 상관없을 것 같지만, 프로젝트 폴더 컨벤션이 잘 안이루어지 느낌이 들었습니다!

2024-05-14 09:46 UTC, kd02109 commented
- carousel 컴포넌트를 범용적으로 사용할 수 있도록 변경했습니다. 
- festival 관련 type을 수정했습니다.
- date formatting을 dayjs 라이브러리를 활용해서 다양한 상황에서 formatting 하도록 수정했습니다.
- component 변경에 의하여 build 오류를 해결했습니다.

2024-05-14 13:17 UTC, hyunwlee-dev approved these changes
고생 많으셨습니다!!
제가 맡고있던 파트가 
캐러셀 -> 카드리스트 형태로 기획이 바뀌어서 기존 캐러셀을 사용하시면 될 것같아요!

2024-05-14 13:17 UTC, hyunwlee-dev commented on app/components/common/hero/hero-tile.tsx
> +*/
주석 삭제 부탁드려욤!

2024-05-14 13:17 UTC, hyunwlee-dev commented on app/components/common/hero/hero-tile.tsx
> +          <span>{description}</span>
위아래 간격이 좀더 벌어져야할 것 같습니다!

2024-05-15 06:47 UTC, ho991217 commented on app/components/common/hero/hero-tile.tsx
> +    <Link href={'#'} className="relative flex-[0_0_100%] overflow-hidden">
`href={'#'}`인데 어떻게 경로 이동이 이루어지나요?

2024-05-15 06:47 UTC, ho991217 commented on app/components/home/lineup-tile.tsx
> +          </Carousel>
어제 논의된 부분 빠르게 반영해주신 것 좋습니다!!

2024-05-15 06:47 UTC, ho991217 commented on app/[locale]/(root-nav)/page.tsx
> +        </Carousel>
빠른 반영 좋습니다 👍👍👍

2024-05-15 06:47 UTC, ho991217 commented on app/components/common/carousel/index.tsx
> +          </div>
이 부분도 컴포넌트로 분리할 수 있지 않을까요?

2024-05-15 06:47 UTC, ho991217 commented on app/components/common/hero/index.tsx
> +  isCarousel?: boolean;
그렇다면 이 부분도 variant가 맞지 않을까요?
하나의 컴포넌트지만 변형된 형태로 존재하는거니까요!

2024-05-15 08:00 UTC, kd02109 commented on app/components/common/carousel/index.tsx
> +          </div>
이부분은 케러셀과 연관되서 사용하기 때문에, 전 하나의 컴포넌트로 관리하는게 좋다고 봤습니다!

2024-05-15 08:01 UTC, kd02109 commented on app/components/home/lineup-tile.tsx
> +          </Carousel>
href={'#'}인데 어떻게 경로 이동이 이루어지나요? 이부분은 추후 서버에서 받은 경로를 토대로 상세 축제 페이지로 이동시키려고 해요. 지금은 아직 페이지 제작이 안되어서 임시로 넣었습니다!

2024-05-15 08:14 UTC, kd02109 commented
추가 수정 사항 반영했습니다.
https://6617cc6b749cda32414848fb-xfxyquyhtu.chromatic.com/

2024-05-16 02:41 UTC, merged